Added example to GetStatus() method.
candlepin/candlepinproject.org pull request #236
Opened 2021-04-30 10:14 UTC by jirihnidek

* Added more information about `GetStatus()` method.
* Described returned JSON document.
* Added example of using `GetStatus()` method
* Fixed another example

2021-04-30 15:00 UTC, ptoscano commented on docs/subscription-manager/dbus_objects.md
> +  The meaning of each item is as follows:
s/item/key/, perhaps? (the same also to all the occurrences that follow)

2021-04-30 15:00 UTC, ptoscano commented on docs/subscription-manager/dbus_objects.md
> +    * `status`: Status of system. This value could be displayed in UI. This string can be localized to some other language. The value should never been used in code for checking the state of system.
if this is translated according to the locale (that is passed as parameter), I'd write it explicitly so; something like:
"This string is a textual description of the status, translated to the specified locale. It can be used in UI strings shown to the user."

2021-04-30 15:00 UTC, ptoscano commented on docs/subscription-manager/dbus_objects.md
> +    * `reason_ids`: Dictionary with reasons, why each product is not entitled or is only partially entitled. Keys of dictionary are IDs of product (99000 in this case). The "key" attribute contains c
maybe quote "key" and "product_name" with `, so they get formatted as monospace

2021-04-30 15:00 UTC, ptoscano commented on docs/subscription-manager/dbus_objects.md
> +    * `reasons`: Textual representation of reasons, why status is invalid. There could be more products that are not entitled and there could be more reasons, why product is not entitled. Strings of
similar as above: if the string is translated, better say it explicitly rather than "can"

2021-04-30 15:46 UTC, tlhmerry9 requested changes
I agree with Pino's comments

2021-04-30 15:46 UTC, tlhmerry9 commented on docs/subscription-manager/dbus_objects.md
> +    * `status`: Status of system. This value could be displayed in UI. This string can be localized to some other language. The value should never been used in code for checking the state of system.
I agree

2021-04-30 15:46 UTC, tlhmerry9 commented on docs/subscription-manager/dbus_objects.md
> +    * `reasons`: Textual representation of reasons, why status is invalid. There could be more products that are not entitled and there could be more reasons, why product is not entitled. Strings of
again agree

2021-04-30 15:46 UTC, tlhmerry9 commented on docs/subscription-manager/dbus_objects.md
> +    * `reason_ids`: Dictionary with reasons, why each product is not entitled or is only partially entitled. Keys of dictionary are IDs of product (99000 in this case). The "key" attribute contains c
good idea in my opinion

2021-05-03 10:14 UTC, jirihnidek commented on docs/subscription-manager/dbus_objects.md
> +    * `status`: Status of system. This value could be displayed in UI. This string can be localized to some other language. The value should never been used in code for checking the state of system.
Thanks for suggestion.

2021-05-04 12:22 UTC, ptoscano commented
Thanks for the changes :+1: LGTM -- Tiff?

2021-05-04 12:54 UTC, tlhmerry9 approved these changes
LGTM also

2021-05-04 12:55 UTC, tlhmerry9 commented
This LGTM also, do you want me to merge this PR?

________________________________
From: Pino Toscano ***@***.***>
Sent: Tuesday, May 4, 2021 7:23 AM
To: candlepin/candlepinproject.org ***@***.***>
Cc: tlhmerry9 ***@***.***>; Comment ***@***.***>
Subject: Re: [candlepin/candlepinproject.org] Added example to GetStatus() method. (#236)


Thanks for the changes 👍 LGTM -- Tiff?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://github.com/candlepin/candlepinproject.org/pull/236#issuecomment-831900321>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AHNY7ERHEUSQSRKUJLW5I4TTL7RK3ANCNFSM43344NOA>.

2021-05-04 13:05 UTC, merged