CANDLEPIN-525: Update for the Conscious Language Initiative
candlepin/candlepinproject.org pull request #275
Opened 2023-04-10 12:22 UTC by wottop

- Remaining references are in URLs to external sites.

2023-04-10 20:20 UTC, JoshAlbrecht23 requested changes
Looks good! I just noticed a broken link and a suggestion to add a line in the commit to include the Dockerfile base image change.

2023-04-10 20:20 UTC, JoshAlbrecht23 commented on _sass/bootstrap/_print.scss
> +// Source: https://github.com/h5bp/html5-boilerplate/blob/main/css/main.css
This link is broken. I think that this was moved to the following url:
https://github.com/h5bp/main.css/blob/main/dist/main.css

2023-04-10 20:20 UTC, JoshAlbrecht23 commented on Dockerfile
> +FROM centos/ruby-27-centos7
I think we should add a line in the commit noting that we are updating the Dockerfile base image. It will make it easier to locate the commit where the base image occurred when looking through the commit history.

2023-04-11 14:52 UTC, Ceiu commented on docs/candlepin/artemis_jobs.md
> +- **candlepin.async.allowlist**<br/>
Most of this entire document is outdated -- updating the verbiage doesn't reflect the current state of the job system configuration.

2023-04-12 16:36 UTC, JoshAlbrecht23 approved these changes
Looks good to me. Once the comment from Chris is addressed it should be good to go

2023-04-18 13:18 UTC, merged